global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'ms-usuarios'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-usuarios:8081']

  - job_name: 'ms-eventos'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-eventos:8082']

  - job_name: 'ms-inventario'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-inventario:8083']

  - job_name: 'ms-reservas'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-reservas:8084']

  - job_name: 'ms-pagos'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-pagos:8085']

  - job_name: 'ms-notificaciones'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ms-notificaciones:8086']
