spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}?currentSchema=eventos
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: eventos
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
