spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}?currentSchema=notificaciones
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: notificaciones
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
